<?php

namespace AppBundle\Repository;

/**
 * ChildrenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildrenRepository extends \Doctrine\ORM\EntityRepository
{
}
