<?php

namespace AppBundle\Repository;

/**
 * MarriagePersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarriagePersonRepository extends \Doctrine\ORM\EntityRepository
{
}
