<?php

namespace AppBundle\Repository;

/**
 * MarriageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarriageRepository extends \Doctrine\ORM\EntityRepository
{
}
