<?php

namespace AppBundle\Repository;

/**
 * ParrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParrentRepository extends \Doctrine\ORM\EntityRepository
{
}
