<?php

namespace AppBundle\Repository;

/**
 * SiblingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiblingsRepository extends \Doctrine\ORM\EntityRepository
{
}
