<?php

namespace AppBundle\Repository;

/**
 * UserPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
